### ISSUE TITLE
Not installable via pip

### ISSUE THREAD

**Issue by jpluscplusm** [aaronbassett/django-GNU-Terry-Pratchett#1]
Thank you for doing this!

It doesn't appear to be installable via pip:
```
$ pip install --verbose django-GNU-Terry-Pratchett
Collecting django-GNU-Terry-Pratchett
  Getting page https://pypi.python.org/simple/django-gnu-terry-pratchett/
  URLs to search for versions for django-GNU-Terry-Pratchett:
  * https://pypi.python.org/simple/django-gnu-terry-pratchett/
  Getting page https://pypi.python.org/simple/django-gnu-terry-pratchett/
  Analyzing links from page https://pypi.python.org/simple/django-gnu-terry-pratchett/
  Could not find any downloads that satisfy the requirement django-GNU-Terry-Pratchett
  Cleaning up...
  No distributions at all found for django-GNU-Terry-Pratchett
  Exception information:
  Traceback (most recent call last):
    File "/Users/ms/balloon/mns/python/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/Users/ms/balloon/mns/python/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/Users/ms/balloon/mns/python/lib/python2.7/site-packages/pip/req/req_set.py", line 333, in prepare_files
      upgrade=self.upgrade,
    File "/Users/ms/balloon/mns/python/lib/python2.7/site-packages/pip/index.py", line 397, in find_requirement
      'No distributions at all found for %s' % req
  DistributionNotFound: No distributions at all found for django-GNU-Terry-Pratchett
```

**Comment by aaronbassett** [comment]
Hi @jpluscplusm I'm not able to recreate. When I run 

```
pip install --verbose django-GNU-Terry-Pratchett
```

it installs as expected. Can you try again and see if you can recreate the issue?

**Comment by jpluscplusm** [comment]
It now works, pulling in version 0.2.0. I /suspect/ Pypi got its package availability / internals in a twist for some reason, and your new release powered its way through the pipeline and solved the problem with prejudice. Ta :-)

**Comment by aaronbassett** [comment]
Awesome, glad it works for you now :+1:
